### ISSUE TITLE
Problem Scaning QR code from extension and Mobile

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-wallet#511]
Trying to scan QR code.

<img width="1423" alt="Screenshot 2020-09-15 at 11 20 25" src="https://user-images.githubusercontent.com/13139371/93185000-91d9de00-f745-11ea-8e03-3be01c0b732e.png">

![IMG_0809](https://user-images.githubusercontent.com/13139371/93185097-b2099d00-f745-11ea-9189-2c0705c09a3a.PNG)

**Comment by etharner** [comment]
For iOS it's an issue which developers of the package can't resolve https://github.com/gruhn/vue-qrcode-reader/issues/196

**Comment by mradkov** [comment]
Can we use a different package instead then?

**Comment by Liubov-crypto** [comment]
I would like to note that it is not very user-friendly that the QR code is in another tab. The "Scan QR" option is located in the "Withdraw" tab, and the required QR code is in the "Top Up" tab. This introduces a little confusion to user actions since when the scan code button is pressed, there is no redirection to the code itself or the scan request.
Maybe we should change sentence under the picture: "Scan QR Code" to "Scan QR Code from Top Up page".
Or do such design as in a base wallet?
![2020-09-21 4 06 41 пп](https://user-images.githubusercontent.com/69896204/93770162-847c9200-fc24-11ea-9710-78bfed680e82.jpg)

Perhaps the user will also be confused by the stylized QR code, under which there is a text: "Scan QR", but this picture is not scanned. 
@mradkov

**Comment by mradkov** [comment]
This is a UX decision. Can be discussed with designers.
