### ISSUE TITLE
Error: n is undefined, Fallback

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-wallet#518]
This issue is blocking the normal behavior of the wallet. Unable to create and send a report. Happens on different occasions, still not able to reproduce it.

![image](https://user-images.githubusercontent.com/13139371/93431089-50c00600-f8cc-11ea-9a16-c32057f10677.png)

**Comment by etharner** [comment]
We have 2 different usings of `n`:
1. https://github.com/aeternity/superhero-wallet/blob/f13f2ff2ee732af932b6eda0a5be37fbe82c7d06/src/popup/utils/helper.js#L230-L231
2. https://github.com/aeternity/superhero-wallet/blob/f13f2ff2ee732af932b6eda0a5be37fbe82c7d06/src/store/mutations.js#L66-L68
This issue probably had the same reason as #520 and was connected to reducing of unaccurate defaultNetworks array (fixed in #522).
Notifications mutation is used only in Notifications screen, and as you had this in unpredictable situations probably this issue shouldn't raise anymore.

**Comment by davidyuk** [comment]
> We have 2 different usings of `n`

Check carefully, this exception may be from minified code

**Comment by CedrikNikita** [comment]
Current version of wallet doesn't have such problems. Feel free to reopen this issue, if it will pop up again.
