### ISSUE TITLE
Design bug when create a new wallet

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#580]
When I was creating a new web wallet I came across a small design bug on the introductory tabs: the word "Ever" slid down a little. It would be nice to fix this:

![Знімок екрана 2020-11-04 о 11 46 28 дп](https://user-images.githubusercontent.com/69896204/98108523-c431cd00-1ea4-11eb-97f1-b8620fdb8475.png)

Browser: Chrome, Version 86.0.4240 (Mac OS)
Superhero ff63864 / v.0.4.0
Mac OS: 10.15.7

**Comment by onvisions** [comment]
I'm sure it wasn't meant to be displayed in this way by design. This issue probably exists for quite some time.

The word "Ever." should be placed
- either immediately after "...funds."
- or **better** - it should remain where it is now BUT **center-aligned**. In this case it will be good if the word "...funds." is not on a separate line  (the text holder should be probably expanded just a little to allow this). 

From the scrrenshot provided the whole text seems a little bit out of alignment. So margins and padding should be checked.
