### ISSUE TITLE
Refreshing the page "logs me out"

### ISSUE THREAD

**Issue by thescientress** [aeternity/superhero-wallet#651]
When refreshing the page, I get logged out. I can quickly log in by clicking log in to web wallet without having to do anything else (no password/private key entry required). Would it make more sense to just not require logging back in unless the user deliberately logs out?

**Comment by CedrikNikita** [comment]
Can you eleborate issue a little more? I don't have such problem using both wallet in iframe and extension.

**Comment by thescientress** [comment]
I go to Superhero.com (with the wallet extension logged in). It doesn't automatically detect my extension so I click "Log in to web wallet." Then it shows that I'm logged in (although showing an old chain name). 

If I refresh the page, it would show the "Log in to web wallet" button again, instead of displaying my wallet logged in.

**Comment by davidyuk** [comment]
Currently, the user can't connect the web wallet and the extension at the same time to UI. And the UI doesn't know if the extension is available or not. So, we are waiting for the extension to connect to UI, or until the user explicitly says that he is going to use the iframe wallet. Related explanation: https://github.com/aeternity/superhero-ui/pull/843.

This issue is not so important in the case of refreshing because UI is not intended to be used this way (until it has bugs). But it may be annoying if I'm working with links to UI shared somewhere else.

As a workaround, we can memorize is the last time the web version was used and enable it immediately. But, won't we have issues if the user decides to install the extension later?

**Comment by CedrikNikita** [comment]
The issue is closed due to inactivity. Feel free to reopen this issue, if it will pop up again.
