### ISSUE TITLE
Error when creating Invite link with FT

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-wallet#847]
Got this error while creating the invite link with FT (small amount 0.1 Davidyuk):
![inv link with FT](https://user-images.githubusercontent.com/69896204/108851243-e5056600-75ec-11eb-93cb-d72f2bf9509b.png)
(it might be good to create such an option for users)

I noticed when I create an invite link with FT, then the amount for some reason is displayed in ae tokens:

https://user-images.githubusercontent.com/69896204/108972087-a4105e80-768b-11eb-8b9f-572c5337b752.mov

**Comment by Liubov-crypto** [comment]
Rechecked, I can create an invite link using FT in the development branch. The amount will be displayed in ae tokens:
![ft invite link ](https://user-images.githubusercontent.com/69896204/112843828-af501300-90ab-11eb-8c88-7ac8a0a76985.png)

**Comment by imollov** [comment]
Apparently, generating invites with FT is not required nor implemented. 

Yet, the issue with displaying wrong token symbol on the screen remains.

**Comment by onvisions** [comment]
@imollov _"Apparently, generating invites with FT is not required nor implemented."_
Not sure about that. I think that logically it has always been intended behavior to create the invite link with the **specific token** selected. Otherwise we shouldn't allow token selection for Invite links at all and generate only AE invite links. However I think that sending different tokens with the invites was supposed to be implemented.  @maxkpower ?

**Comment by CedrikNikita** [comment]
Yo cannot use tokens without AE, so it's not user friendly to five them tokens via invite, but no AE.

**Comment by imollov** [comment]
@onvisions 

> Yet, the issue with displaying wrong token symbol on the screen remains.

fixed in #1025 - you can test on the preview there

**Comment by onvisions** [comment]
Tested. Seems ok now regarding the issue described above.
