### ISSUE TITLE
The recent transaction list on the main page has a limited height (cropped)

### ISSUE THREAD

**Issue by davidyuk** [aeternity/superhero-wallet#880]
| Master | Develop |
|---|---|
| ![photo_2021-03-10_21-21-02](https://user-images.githubusercontent.com/9007851/110677772-99ef7380-81e6-11eb-8853-892fc8d6f581.jpg) | ![photo_2021-03-10_21-21-05](https://user-images.githubusercontent.com/9007851/110677775-9a880a00-81e6-11eb-9353-e9909bac3cbf.jpg) |

The version in develop branch has more items in the recent transaction list, but that list has a limited height and scrollable inside. For me would be more reasonable to don't limit it and allow it to be scrolled with the entire page as it was before. Seems that designs doesn't explicitly define this: 
https://www.figma.com/file/ewTV7C01eFlKVODGHokUI0/Superhero-Wallet-UI?node-id=3662%3A0

**Comment by imollov** [comment]
In general I agree with your proposal. 

Regarding the version in develop - it's implemented as specified! (with a few minor exceptions which I'll fix together with refactorings)

Have you checked these?
* the interactive prototype: https://www.figma.com/proto/ewTV7C01eFlKVODGHokUI0/Superhero-Wallet-UI?node-id=1%3A5&scaling=min-zoom
* in figma desings: 
![Screenshot 2021-03-12 at 10 20 06](https://user-images.githubusercontent.com/482351/110912382-8ba37380-831c-11eb-9c41-261bf8403cc0.png)
* the number of items in the list is synced with @onvisions

**Comment by davidyuk** [comment]
Ok, I see. At least we can stretch the translation list to the end of the screen, keeping it scrollable inside.

**Comment by onvisions** [comment]
1. Seems like we are missing the bottom menu (that's part of new design) and that's the reason for the empty area at the bottom of the viewport. 
2. For the web wallet I asked for predefined max-height of the extension (it's 640px in the prototype because it's covering standard aspect ratio for mobile screens but for desktop we can increase it to 700px to have more space and to avoid scrolling). Also for borders as it's done in the prototype. What we previously had (100% height filling the browser viewport on desktop) didn't look good at all. Some screens have less content others such as scrollable lists have considerably longer so the result is "jumping" when clicking and inconsistent look and feel.

**Comment by onvisions** [comment]
After syncing with @imollov I'm suggesting the following approach to extension height:

1. Deafult height in design is 640px (as in the Android standard ratio of 360px width and 640px height ). More about this has been previously commented here about 20 days ago: https://github.com/aeternity/superhero-wallet/pull/820#discussion_r584596375 (**regarding the fix of the web wallet index page which hasn't been applied yet as far as I can see...**)

On Chromium based browsers the height limitation is 600px. So the max-height for chromium browsers will be set to 600px. For all other the extension will be 640px as by design.

2. For the web wallet I suggest to have the max-height limited to 740px (as we obviously have more space on desktop devices that we can utilize). I don't think that the height should be set to "auto" or "100%" as some screens have way more content than others and the UI is visibly "jumping" which ruins the UX. I suggest having fixed height of 740px and fram border around the wallet as it's done in Web wallet design in Figma. The only difference will be that now I suggest adding 100px to the height on desktop devices (we can afford it on desktop devices).

I think this is all doable with min-height, max-height and percentage values but I'm leaving the exact approach to devs here. 

@maxkpower @mradkov , do you agree with this approach to dealing with wallet height?

**Comment by etharner** [comment]
Done in #872.
